### ISSUE TITLE
Test report

### ISSUE THREAD

**Issue by parhamin2010** [pondersource/oc-opencloudmesh#16]
The scenario I did. 
First I added a new user in oc1 (parhamoc1) in new group (oc1test) and addded a new user in oc2 (parhamoc2) in new group (oc2test) and try to share a new folder from oc1 to new added user (parhamoc2) used its group (oc2test@oc2.docker). 

1- On dev-stock main branch there's no files based on the instruction in [document](https://github.com/pondersource/oc-opencloudmesh#development).
> there should be some replacement based on the latest changes on oc-opencloudmesh-testing branch on dev-stock
> 1- ./scripts/init-oc-opencloudmesh.sh
> 2- ./scripts/init-rd-sram.sh 
> 3- ./scripts/oc-opencloudmesh-testing.sh 

![image](https://github.com/pondersource/oc-opencloudmesh/assets/25672014/a22cbcc4-6383-459b-bd26-31468a1fb2e9)
![image](https://github.com/pondersource/oc-opencloudmesh/assets/25672014/2e13f1c1-b1a5-45e2-bb64-77311ca52933)

That's it. I couldn't find any other issues.

**Comment by navid-shokri** [comment]
@MahdiBaghbani @yasharpm can you help us to find the 
> ./scripts/init-gitpod-prebuild.sh file
or make it clear to us, what should be the correct command for running the test environment?

**Comment by navid-shokri** [comment]
:information_source: 
I found all of these files there :thinking: 
https://github.com/pondersource/dev-stock/tree/main/scripts

**Comment by parhamin2010** [comment]
@navid-shokri as I checked with @yasharpm . he said that he used [this](https://github.com/pondersource/dev-stock/tree/oc-opencloudmesh-testing/scripts) for dev stock testing so I tested with that and files doesn't exists. 
but, as we discussed we should use main branch or ocm accept share instead of that one.

**Comment by michielbdejong** [comment]
The document now says:
```
To debug it, you can open https://github.com/pondersource/dev-stock on GitPod and run:

./scripts/init-opencloudmesh.sh
./scripts/testing-opencloudmesh.sh.

**Comment by parhamin2010** [comment]
# Good working! 
Test passed on main branch.

![image](https://github.com/pondersource/oc-opencloudmesh/assets/25672014/12bb450e-3002-49eb-9f4b-227fff830967)
![image](https://github.com/pondersource/oc-opencloudmesh/assets/25672014/a47a1f9d-331d-4824-9011-b8e6aa9e2713)

**Comment by michielbdejong** [comment]
Great! Thanks for your testing!
