### ISSUE TITLE
unshare doesn't stick

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/oc-opencloudmesh#20]
When Marie browses to 'shared with you' and unshares something, it disappears from the list. but then when she refreshes the page, it reappears.
<img width="1121" alt="Screenshot 2023-06-22 at 14 23 05" src="https://github.com/pondersource/oc-opencloudmesh/assets/408412/f502bd83-649b-4ae9-a3b9-dc885d9d78f3">

**Comment by michielbdejong** [comment]
To confirm, this is with the instructions from https://github.com/pondersource/oc-opencloudmesh#development so only opencloudmesh app installed, and not the federatedgroups app.

**Comment by navid-shokri** [comment]
ℹ 
I found the problem:
when we are clicking on unshare button there is an error:
 
{"reqId":"RtC9XZDxpHcnUNyUz7Nh","level":3,"time":"2023-06-28T07:18:41+00:00","remoteAddr":"172.19.0.2","user":"marie","app":"PHP","method":"DELETE","url":"\/remote.php\/dav\/files\/marie\/machine-id","message":"Undefined index: id at \/var\/www\/html\/apps\/oc-opencloudmesh\/opencloudmesh\/lib\/Files_Sharing\/External\/Manager.php#314"}

**Comment by navid-shokri** [comment]
problem can be found on https://github.com/pondersource/oc-opencloudmesh/commit/1b3eeb6122e1c401f392850f29a2dd53d52e7666

and is fixed on https://github.com/pondersource/oc-opencloudmesh/commit/0122e229506e7954eceb769fa1791732084d7d96
