### ISSUE TITLE
Compatiblity with the nextcloud Federated group sharing.

### ISSUE THREAD

**Issue by navid-shokri** [pondersource/oc-opencloudmesh#22]
:question: 

did we test our ocm-opencloudmesh compatibility with Nextcloud? if the answer is NO, so, Should we do?
I was thinking what if someone tries to share a file with a group without any information about the cloud-sharing system?
is it expected that our app should deal with the Nextcloud app?

**Comment by navid-shokri** [comment]
:information_source: 

So based on @yasharpm answer this test is not done but we expect that this ability should be unleashed.

**Comment by michielbdejong** [comment]
good point! yes, we should test both NC sender -> OC group and OC sender -> NC group

**Comment by navid-shokri** [comment]
@MahdiBaghbani please proper a dev-stock environment that contains these building blocks:

1- installed pure Nextcloud. 
2- installed Owncloud including the oc-opencloudmesh application.

**Comment by MahdiBaghbani** [comment]
We already have it. both ownCloud and Nextcloud have base installations from the official source without extra apps or settings.
We also have opencloudmesh image as the base image for our rd-SRAM image.

What exactly do you want that doesn't exist?

**Comment by navid-shokri** [comment]
ℹ 
@MahdiBaghbani 
as I describe it to you we want a configured environment like `testing-opencloudmesh.sh` or `testing-rd-sram.sh`

**Comment by MahdiBaghbani** [comment]
I hope this works for you:
https://github.com/pondersource/dev-stock/blob/main/scripts/testing-ocm-nc-oc.sh

**Comment by navid-shokri** [comment]
Scenario 1‍⃣ :
❓ Share a file from OC ---> NC (remote group)
**Result:**
🟢  it was working 


Scenario 2‍⃣ :
❓ Share a file from NC ---> OC (remote group)
**Result:**
🟢  it was working 


Scenario 3‍⃣  :
❓ unshare the shared file from OC ---> NC (remote group)
**Result:**
🟢  it was working 

Scenario 4‍⃣ :
❓ unshare the shared file from NC ---> OC (remote group)
**Result**: 
🟢  it was working 

Scenario 5‍⃣ :
❓ delete the shared file from NC (the shared file from OC ---> NC (remote group))
**Result**: 
🔴  it does not stick
**Description:** 
When I click on the `leave this share` button on the NC it will be disappeared but when I refresh the page the confirm share will be prompted again. it is addressed in issue https://github.com/pondersource/oc-opencloudmesh/issues/29

**Comment by navid-shokri** [comment]
Scenario 6‍⃣  :
:question: delete the shared file from OC (the shared file from NC ---> OC (remote group))
**Result:**
:green_circle: it does not stick

**Comment by navid-shokri** [comment]
Scenario 7‍⃣   :
:question: reshare the shared file from OC locally (the shared file from NC ---> OC (remote group))
**Result:**
🟡  it is shared but the next cloud is not aware of this local sharing on OC.

**Comment by navid-shokri** [comment]
Scenario 7‍⃣   :
:question: reshare the shared file from OC remotely (the shared file from NC ---> OC (remote group))
**Result:**
🔴  "File is already shared" with the reshare@nc2.docker
Description : 

I shared a file from NC ---> OC (remote group) 
and then reshare the file with another group on NC
and It failed. the issue is addressed in issue https://github.com/pondersource/oc-opencloudmesh/issues/30

**Comment by navid-shokri** [comment]
Scenario 8‍⃣    :
:question: reshare the shared file from NC remotely (the shared file from OC ---> NC (remote group))
**Result:**
🔴  "File is already shared" with the reshare@oc1.docker
Description : 

I shared a file from OC ---> NC (remote group) 
and then reshare the file with another group on NC
and It failed. the issue is addressed in issue https://github.com/pondersource/oc-opencloudmesh/issues/30
