### ISSUE TITLE
init-gitpod-prebuild.sh should be reviewed

### ISSUE THREAD

**Issue by navid-shokri** [pondersource/oc-opencloudmesh#24]
in this script, we are trying to pull a lot of images that are not related to oc-opencloudmesh, So, we are wasting a lot of resources and time.

```
docker pull rclone/rclone:latest
docker pull collabora/code:latest
docker pull cs3org/wopiserver:latest
docker pull pondersource/dev-stock-revad:latest
docker pull pondersource/dev-stock-ocmstub:latest
docker pull pondersource/dev-stock-nextcloud-sciencemesh:latest
docker pull pondersource/dev-stock-nextcloud-mfa:latest
docker pull pondersource/dev-stock-nextcloud-solid:latest
docker pull pondersource/dev-stock-owncloud-sciencemesh:latest\
```
It seems these are redundant and useless

**Comment by MahdiBaghbani** [comment]
Gitod needs to be prebuilt for everyone and not only opencloudmesh. they are not useless and You should not use them locally and only in a cloud environment.
Usually in Gitpoid and Codespaces with fast internet, it is done under 1 minute.

Are you trying to pull images into your own computer?

Also, why are you opening dev-stock issue in this repo?
