### ISSUE TITLE
opencloudmesh app is not listed in enabled apps

### ISSUE THREAD

**Issue by navid-shokri** [pondersource/oc-opencloudmesh#27]
I cannot manipulate the app using the panel:

![Image](https://github.com/pondersource/oc-opencloudmesh/assets/123634558/67d0851f-ffae-4508-a6e3-4ca63849fb67)

but the application is installed 

![Image](https://github.com/pondersource/oc-opencloudmesh/assets/123634558/bb82b3ce-a905-4ba5-864d-488124a23cb9)

**Comment by navid-shokri** [comment]
I guess I found the cause: 
application is installed but with the wrong Name: `Federated Groups`

**Comment by MahdiBaghbani** [comment]
Yes, that's, the case, you have to change its name here:
https://github.com/pondersource/oc-opencloudmesh/blob/1b3eeb6122e1c401f392850f29a2dd53d52e7666/opencloudmesh/appinfo/info.xml#L4
