### ISSUE TITLE
Publish OCM in the marketplace

### ISSUE THREAD

**Issue by thepeak99** [pondersource/oc-opencloudmesh#5]

**Comment by thepeak99** [comment]
@MahdiBaghbani do you have an update about this topic?

**Comment by MahdiBaghbani** [comment]
We are waiting for ownCloud to issue certificates for us.

https://github.com/owncloud/appstore-issues/issues/178
https://github.com/owncloud/appstore-issues/issues/179

**Comment by MahdiBaghbani** [comment]
Tagged and Released in Github:
https://github.com/pondersource/oc-opencloudmesh/releases/tag/v0.1.1-oc

Published in ownCloud marketplace:
https://marketplace.owncloud.com/apps/opencloudmesh
